### ISSUE TITLE
Download executable 

### ISSUE THREAD

**Issue by haesleinhuepf** [elgw/dw_gui#18]
Hi @elgw ,

congrats to this great tool! Do you think it would be possible to offer compiled executables / installers for end-users? You know many scientists who would use you tool do not know how to deal with makefiles...

Thanks!

Best,
Robert

**Comment by elgw** [comment]
Hi Robert, and thanks!

I completely agree with you that it would be great to provide downloadable installers/pre-packaged binaries here.

For Ubuntu 22 and 24 that would not a big deal to add. On the other hand it would not add much value since the install instructions are pretty straight forward. For all other platforms (that I'm not using) it would be a bigger effort to set up cross-compiling, especially for MacOS that I don't have access to at all and would not be able to test.

The GUI is nothing complicated (at the moment) and I've even toyed with the idea to have a HTML/javascript based command line builder for it, possibly on a Python/FLASK backend or something similar so that it could also run things. That would be much more portable than the current GTK based interface.

Cheers,
Erik

**Comment by haesleinhuepf** [comment]
> For all other platforms (that I'm not using) it would be a bigger effort to set up cross-compiling, especially for MacOS that I don't have access to at all and would not be able to test.

A potential way out: Do you have colleagues who use Mac or Windows? They could compile a version that you offer to download here. That way new users could try out the tool, even if it might not be the very last version.

**Comment by elgw** [comment]
I got my hands on a windows machine and made the adjustments needed to compile it. There is an installer under [releases](https://github.com/elgw/deconwolf-gui/releases/). I will continue to update for windows but I don't have any plans for MacOS at the moment.

**Comment by haesleinhuepf** [comment]
Amazing, thanks so much for spending time on this!!
